In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# ls

In [5]:
tickets = pd.read_csv('anonymized_hubspot_tickets.csv')
deals = pd.read_csv('anonymized_hubspot_deals.csv')
companies = pd.read_csv('anonymized_hubspot_companies.csv')

/var/folders/vs/xwzq4hsj1lz9tz8k9jz_tw540000gn/T/ipykernel_20306/2095908849.py:3: DtypeWarning: Columns (24,25,28,32,45) have mixed types. Specify dtype option on import or set low_memory=False.
  companies = pd.read_csv('anonymized_hubspot_companies.csv')

In [75]:
deals.columns

Index(['Weighted amount', 'Deal Description',
       'Cumulative time in "BANT Deal. Pain ID'ed (Sales Pipeline)" (HH:mm:ss)',
       'Cumulative time in "Opportunity (Sales Pipeline)" (HH:mm:ss)',
       'Days to close', 'Deal Score', 'Close Date',
       'Deal source attribution 2',
       'Cumulative time in "In Trial - Trial in Progress (Sales Pipeline)" (HH:mm:ss)',
       'Contract Start Date',
       'Cumulative time in "Partner Referrals  (Sales Pipeline)" (HH:mm:ss)',
       'Cumulative time in "Closed Lost (Sales Pipeline)" (HH:mm:ss)',
       'Cumulative time in "Deep Dive. PSP Drafted (Sales Pipeline)" (HH:mm:ss)',
       'Pipeline', 'Record ID', 'Forecast category', 'Original Traffic Source',
       'Associated Company', 'Deal owner', 'Annual contract value',
       'Is Closed (numeric)', 'Amount in company currency',
       'Annual recurring revenue', 'Monthly recurring revenue',
       'Deal probability', 'Associated Company (Primary)', 'Is Closed Won',
       'Forecast probability', 'Contract End Date', 'Last Activity Date',
       'Contract Term (Months)', 'Trial Start date', 'Is closed lost',
       'Weighted amount in company currency', 'Is Deal Closed?',
       'Trial End Date', 'Deal Name', 'Amount',
       'Cumulative time in "Closed Trial (Sales Pipeline)" (HH:mm:ss)',
       'Forecast amount',
       'Cumulative time in "Negotiation (Sales Pipeline)" (HH:mm:ss)',
       'Is Open (numeric)',
       'Cumulative time in "Renewals  (Sales Pipeline)" (HH:mm:ss)',
       'Create Date',
       'Cumulative time in "Contract Sent (Sales Pipeline)" (HH:mm:ss)',
       'Total contract value', 'Last Modified Date',
       'Cumulative time in "Closed Won (Sales Pipeline)" (HH:mm:ss)',
       'Deal Stage', 'Deal Type', 'Company ID'],
      dtype='object')

In [77]:
deals[['Deal Description','Days to close', 'Is Deal Closed?', 'Is Closed Won','Deal Stage']]

,Deal Description,Days to close,Is Deal Closed?,Is Closed Won,Deal Stage
0,40-50 employees,69.0,False,False,Opportunity
1,"3,000 + Agents.",149.0,False,False,Partner Referrals
2,5-6k agents,149.0,False,False,Partner Referrals
3,Furthest Along - 300 agents,149.0,False,False,Partner Referrals
4,BPO through partnership with AmplifAI,120.0,False,False,Deep Dive. PSP Drafted
...,...,...,...,...,...
588,Development of training Syms for the transitio...,131.0,True,True,Closed Won
589,NaN,131.0,True,True,Closed Won
590,New project with Retail Services. Citi L&D gr...,131.0,True,True,Closed Won
591,Seasonal Hurricane Support for New Hires,246.0,True,True,Closed Won
592,Create a new renewal term,134.0,True,True,Closed Won

In [55]:
### column names of the companies dataset
companies.columns

Index(['Parent Company', 'CCaaS', 'Annual Revenue', 'Target Account',
       'Associated Contact', 'Number of Form Submissions', 'Total Agents',
       'Web Technologies', 'Close Date', '# of Agents Total',
       'Number of times contacted', 'Contact with Primary Company',
       'ICP Fit Level', 'Revenue range', '# of Agents Contracted', 'Record ID',
       'Time Zone', 'Primary Industry', 'Number of Pageviews',
       'Primary Company', 'Year Founded', 'ICP', 'Industry group',
       'Segmentation', 'LMS System', 'SymTrain Use Cases',
       'Associated Company', 'BPO', 'SSO Application', 'State/Region',
       'SymTrain Product', 'Contract End Date', 'SSO Implemented?',
       'Consolidated Industry', 'Type', 'Number of Employees', 'BPO Program',
       'Primary Sub-Industry', 'Number of Sessions', 'WFM', 'Country/Region',
       'Industry', 'Create Date', 'Company name', 'Last Modified Date',
       'BPO Program Tier'],
      dtype='object')

In [57]:
### column names of the ticket dataset
tickets.columns

Index(['Create date', 'Ticket Tags', 'Stage Date - Project Launch',
       'Associated Contact', 'Category', 'Target Launch Date', 'Kickoff Call',
       'Close date', 'Pipeline', 'Stage Date - Project Initiation',
       'Stage Date - Planning Phase', 'Ticket status',
       'Stage Date - Execution', 'Time to first agent email reply (HH:mm:ss)',
       'Last CES survey rating', 'Priority', 'Associated Company',
       'Who will be creating the Syms?', 'Stage Date - Closure Phase',
       'Stage Date - Monitoring and Control Phase',
       'Associated Company (Primary)', 'Response time (HH:mm:ss)', 'Ticket ID',
       'Time to close (HH:mm:ss)', 'Associated Deal', 'Library index approved',
       'Training: General Overview', 'Latest Milestone',
       'Training: Deployment/User Management Training',
       'Requirements for the Trial', 'Training: Sym Building 101',
       'Last modified date', 'Type', 'Trial End Date',
       'Training: Sym Building 201', 'Stage Date - Converted Won',
       'Latest Milestone Update Date', 'Ticket name', 'Trial Overview',
       'Trial Start Date', '1st Syms presented for review',
       'Project Launch Day', 'Training: Reporting',
       'Construction of 1st Sym begun', 'Trial Required', 'Was the sym QAed?'],
      dtype='object')

In [63]:
set(deals['Deal Stage'])

{"BANT Deal. Pain ID'ed",
 'Closed Lost',
 'Closed Trial',
 'Closed Won',
 'Contract Sent',
 'Deep Dive. PSP Drafted',
 'In Trial - Trial in Progress',
 'Negotiation',
 'Opportunity',
 'Partner Referrals ',
 'Renewals '}

In [79]:
companies.columns

Index(['Parent Company', 'CCaaS', 'Annual Revenue', 'Target Account',
       'Associated Contact', 'Number of Form Submissions', 'Total Agents',
       'Web Technologies', 'Close Date', '# of Agents Total',
       'Number of times contacted', 'Contact with Primary Company',
       'ICP Fit Level', 'Revenue range', '# of Agents Contracted', 'Record ID',
       'Time Zone', 'Primary Industry', 'Number of Pageviews',
       'Primary Company', 'Year Founded', 'ICP', 'Industry group',
       'Segmentation', 'LMS System', 'SymTrain Use Cases',
       'Associated Company', 'BPO', 'SSO Application', 'State/Region',
       'SymTrain Product', 'Contract End Date', 'SSO Implemented?',
       'Consolidated Industry', 'Type', 'Number of Employees', 'BPO Program',
       'Primary Sub-Industry', 'Number of Sessions', 'WFM', 'Country/Region',
       'Industry', 'Create Date', 'Company name', 'Last Modified Date',
       'BPO Program Tier'],
      dtype='object')

In [83]:
companies.head()

,Parent Company,CCaaS,Annual Revenue,Target Account,Associated Contact,Number of Form Submissions,Total Agents,Web Technologies,Close Date,# of Agents Total,...,BPO Program,Primary Sub-Industry,Number of Sessions,WFM,Country/Region,Industry,Create Date,Company name,Last Modified Date,BPO Program Tier
0,NaN,NaN,1.000000e+09,NaN,Contact_ef780380,0.0,NaN,Route 53,NaN,NaN,...,NaN,NaN,0.0,NaN,United States,HVAC and plumbing supply,2024-10-30 10:51,Company_4fc73a2a,2025-02-14 13:39,NaN
1,NaN,NaN,NaN,NaN,Contact_93373ba5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Pest Control,2024-09-12 18:30,Company_f3f7e884,2025-02-14 13:39,NaN
2,NaN,NaN,5.000000e+07,NaN,Contact_2e8e0993,0.0,NaN,Youtube; App Nexus; Google Tag Manager; Facebo...,NaN,NaN,...,NaN,NaN,0.0,NaN,United States,Pest Control,2024-09-03 10:44,Company_89929bed,2025-02-14 13:39,NaN
3,NaN,Five9,5.000000e+07,NaN,Contact_635e44ed,0.0,NaN,Postmark; Facebook Advertiser; Salesforce; Goo...,NaN,NaN,...,NaN,NaN,0.0,NaN,United States,Pest Control,2024-08-02 11:36,Company_33dbf591,2025-02-14 13:39,NaN
4,NaN,Five9,1.000000e+08,NaN,Contact_8d055096,0.0,NaN,Microsoft Office 365; Google Tag Manager; Reca...,NaN,NaN,...,NaN,NaN,0.0,NaN,United States,Pest Control,2024-08-02 11:36,Company_a3079821,2025-02-14 13:39,NaN

# load the mapping json file

### The mapping json file contains the dictionaries that can be used to map any of the 2 files together

In [89]:
### read in the mapping file
import json

with open('mappings.json', 'r') as f:
    mappings = json.load(f)

### check the keys
print(f'mapping keys: {mappings.keys()}')

mapping keys: dict_keys(['CompanyToDeals', 'CompanyToTickets', 'ParentChildRelationships', 'TicketToDeal'])

- `CompanyToDeals`: contains the mappings from company ID to Deals ID
- `CompanyToTickets`: contains the mappings from company ID to Tickets ID
- `TicketToDeal`: contains the mappings from Ticket ID to Deal ID

# Map company and deals dataset

### In order to map the company data and the deals data, we need to first create a one to one mapping between the deals ID and the company ID based on mappings['CompanyToDeals']

In [97]:
# revert the company-deal mapping
deal_to_company = {}

for company_id, deal_list in mappings["CompanyToDeals"].items():
    for deal_id in deal_list:
        deal_to_company[deal_id] = company_id
deal_to_company

{'29547238775': '17771181752',
 '9794988112': '9364308545',
 '9817334075': '9366087515',
 '9817334090': '9366136383',
 '9817320072': '9366140751',
 '9817329956': '9366155050',
 '9817302616': '9366059421',
 '9817306699': '10557622578',
 '9817320073': '9366110525',
 '9783091342': '9355871862',
 '9783148315': '9355871862',
 '9784284936': '9355871862',
 '9784357419': '9355871862',
 '9816968255': '9355871862',
 '9816996368': '9355871862',
 '9816996373': '9355871862',
 '9816996374': '9355871862',
 '9817292301': '9355871862',
 '9817306701': '9355871862',
 '9817311102': '9355871862',
 '9817320086': '9355871862',
 '11993267974': '9355871862',
 '12925391644': '9355871862',
 '22424270143': '9355871862',
 '30181727847': '29943445034',
 '33724679941': '21636976812',
 '32118663507': '21413800792',
 '22254233163': '21413988657',
 '22086573062': '21377449362',
 '18875629455': '19683377975',
 '18246568357': '19634937444',
 '33503208981': '18832393786',
 '17891673997': '17734212240',
 '22813103370': '17734212240',
 '21300551716': '28941996658',
 '33352193280': '16275376238',
 '13913191733': '16206048635',
 '22412744791': '16206048635',
 '23375900245': '16206048635',
 '14234455660': '16158303562',
 '33514107559': '29830434115',
 '28758159921': '15581709337',
 '12290125701': '14806346252',
 '15449641791': '14806346252',
 '16897887630': '14806346252',
 '32114215222': '28652048703',
 '29874514335': '12067978625',
 '31934084477': '12073489820',
 '17445956470': '11466024279',
 '11834219135': '10733490991',
 '14418104484': '10733490991',
 '22549172369': '10733490991',
 '18760220715': '10558877741',
 '11764379525': '10558217137',
 '16495966644': '10558217137',
 '21113223987': '10558217137',
 '18733026936': '10558127988',
 '19393070415': '29511582475',
 '22539098185': '29511582475',
 '31622911152': '29511582475',
 '23172924024': '10348232276',
 '17304537772': '21636407854',
 '19091997620': '15566796315',
 '11570483865': '29840888747',
 '14796495288': '10348179895',
 '18732749183': '10348156822',
 '14211778391': '9968885525',
 '12243057957': '11658771267',
 '13981816904': '11658771267',
 '16476598933': '11658771267',
 '16913229846': '11658771267',
 '16913230613': '11658771267',
 '9870401327': '9417598342',
 '16913145261': '9417598342',
 '16589140661': '29906584881',
 '23142937010': '9366141068',
 '15939940435': '9366092049',
 '18150169965': '9366092049',
 '16701688672': '9366124418',
 '9817306698': '18475337759',
 '10874517338': '18475337759',
 '15124574762': '18475337759',
 '22424217480': '18475337759',
 '31660153986': '18475337759',
 '18151281470': '9363378602',
 '13506983093': '9363073402',
 '14377129033': '9363073402',
 '11310201388': '17733969334',
 '14217892146': '25472592721',
 '16913142871': '25472592721',
 '18731091569': '10348224656',
 '18151204418': '29863187609',
 '10083572533': '9349628249',
 '13588945588': '9349628249',
 '13835319382': '16210149704',
 '30366316072': '26943605027',
 '13525575499': '11660991668',
 '17634649483': '11660991668',
 '22681760840': '11660991668',
 '9816981916': '16780204169',
 '9816958783': '9366155047',
 '16909950725': '18698826840',
 '13714981258': '15850993189',
 '13546752697': '15851784045',
 '17020638329': '10332057652',
 '17518537382': '10089603993',
 '10881763501': '9979656496',
 '11764517718': '9980123213',
 '10881745030': '9980059039',
 '9817292294': '9366149809',
 '9817297167': '29909240464',
 '9816991509': '12080807196',
 '18693595992': '20274385567',
 '18380671412': '16192170517',
 '16970826403': '15726727984',
 '12873538401': '15406426391',
 '9816968248': '9366119473',
 '9817297177': '9366119473',
 '9817334083': '9366119473',
 '20329423023': '9366119473',
 '28866556591': '9366119473',
 '9816991499': '29908438347',
 '9816972350': '9366128723',
 '9816996380': '9366128723',
 '9817302610': '9366128723',
 '9817334074': '9366128723',
 '9817334078': '9366128723',
 '9817302620': '9366172835',
 '9805752633': '9366103838',
 '9817297173': '29829201035',
 '13134551697': '9360832404',
 '32323647596': '10558860645',
 '13886657569': '15852049802',
 '12103623186': '12012777239',
 '14545852989': '11466483988',
 '17887715615': '11466483988',
 '32325340702': '11466483988',
 '28423882503': '10558210732',
 '9817287471': '9366099384',
 '9817320081': '29944777595',
 '20482040998': '10356057716',
 '21669003882': '17747626287',
 '23172923267': '17772183386',
 '30462267311': '15597193294',
 '22458911851': '29916351637',
 '12270134701': '13560835382',
 '33499007642': '29965090080',
 '29545199489': '23228101132',
 '22200267917': '22946663759',
 '17618748967': '19014212411',
 '33428494649': '19014212411',
 '14997595409': '16892177021',
 '14575314266': '16689309363',
 '15754827596': '16275230554',
 '23317813521': '16275222365',
 '22549184338': '17350078828',
 '23245883816': '12538653231',
 '17874320388': '12551290635',
 '19190491061': '12551290635',
 '19009950725': '10557622626',
 '17983738886': '9980232037',
 '10858787222': '9732328558',
 '15691158188': '9732328558',
 '16912814241': '9732328558',
 '9816972343': '9363076424',
 '14542844254': '9363076424',
 '20009427593': '9363076424',
 '30914795108': '9363076424',
 '31660157212': '9363076424',
 '21173715782': '14126783254',
 '18151204729': '10558244510',
 '20242942753': '20654962243',
 '10757379478': '9812599703',
 '9816986926': '25481208412',
 '12854398239': '16281658149',
 '16235870300': '25481208412',
 '29772670982': '25033555780',
 '20482041196': '21693826634',
 '14726829882': '15851956499',
 '31930752356': '16279026360',
 '12091214396': '12067836436',
 '13981934856': '12067836436',
 '16913186570': '12067836436',
 '31999369068': '12067836436',
 '18760957036': '22018764067',
 '21094179915': '22018764067',
 '22568943391': '22018764067',
 '12038760465': '12012857372',
 '22090648230': '15356584486',
 '15220484379': '12551350123',
 '18761012365': '20357572130',
 '28713158659': '16275387974',
 '18151282954': '15767528372',
 '14341861532': '15449264301',
 '16276236692': '15449264301',
 '18151201200': '16259826285',
 '22863736667': '16259826285',
 '31622890817': '16259826285',
 '18731955382': '9366150209',
 '14008462659': '16036961628',
 '22413073409': '16036961628',
 '11311077008': '10258890386',
 '10881745185': '9955266454',
 '21173838851': '21529949109',
 '18508596616': '19281190936',
 '16701702428': '18322627086',
 '22813468222': '18322627086',
 '20298991512': '16275274589',
 '18846917002': '19899638853',
 '22813842453': '19899638853',
 '33452127129': '19899638853',
 '18151205655': '12551531444',
 '32323660311': '28576113207',
 '33774471298': '16279026432',
 '17904955520': '16017583144',
 '12578881135': '15027678893',
 '16897886068': '15027678893',
 '18378867117': '9645904458',
 '18034421090': '15597271344',
 '14574414463': '29543474616',
 '14785508700': '10558877735',
 '13048072971': '14913166694',
 '18380307239': '10558176615',
 '20819262787': '10558176615',
 '17528360813': '10558126494',
 '17028782009': '29942545664',
 '19202369890': '9669918864',
 '9816940654': '9645904458',
 '9816991497': '9645904458',
 '9816991505': '9645904458',
 '12279252011': '9645904458',
 '13539295668': '9645904458',
 '22813472362': '9645904458',
 '12191175776': '9499343195',
 '14556037646': '9499343195',
 '16883544924': '9499343195',
 '16913185376': '9499343195',
 '18033099342': '9499343195',
 '21004614213': '9499343195',
 '22340729779': '9499343195',
 '9817292308': '9366136384',
 '29545199948': '9366119474',
 '9816972337': '9366078523',
 '9817287474': '10558188033',
 '9817339732': '9366059423',
 '22643138974': '9366059423',
 '9817287476': '9366119470',
 '9816940660': '10558217378',
 '9816968244': '10558217378',
 '9816968250': '9366164276',
 '9816991502': '9366164276',
 '9816996371': '9366164276',
 '9817329961': '9366164276',
 '9816977215': '9366119466',
 '9817287488': '9366119466',
 '22430126207': '9364004269',
 '11579853598': '25476599079',
 '16809646512': '25476599079',
 '9789640630': '29828266075',
 '9789682209': '29828266075',
 '9816958792': '29828266075',
 '9816968249': '29828266075',
 '9816981925': '29828266075',
 '9816996389': '29828266075',
 '9817339733': '29828266075',
 '12626572587': '29828266075',
 '18729346199': '29828266075',
 '9771980923': '29543474616',
 '18033237356': '9349708053',
 '9816953951': '10558847651',
 '18033106089': '10558847651',
 '9756567218': '9338114710',
 '9816958786': '9338114710',
 '9816963432': '9338114710',
 '9816972342': '9338114710',
 '9817306700': '9338114710',
 '32403166800': '9338114710',
 '18151281758': '10558088025',
 '18151282572': '10558854434',
 '18761129128': '10558854434',
 '18380619941': '29927793964',
 '9817334077': '9366172846',
 '21231151119': '9363227152',
 '18151025724': '19543627275',
 '13512856226': '9352811279',
 '15884117814': '17747228501',
 '15754783784': '17734791853',
 '20634942017': '17734791853',
 '19974759242': '15566796315',
 '18034263123': '10348294442',
 '11665797173': '9824377096',
 '9817320093': '9366106652',
 '9816996372': '16082213790',
 '9817302613': '16082213790',
 '9816977201': '9366091670',
 '9817334081': '9366091670',
 '9816946084': '22355412368',
 '12074424995': '22355412368',
 '17891674183': '22355412368',
 '21070059926': '22355412368',
 '11636340366': '29917451401',
 '17158807082': '18841868726',
 '18150341990': '17555659546',
 '14997026612': '17075395144',
 '22413072747': '17075395144',
 '29857459859': '25473520407',
 '13540347499': '15851984185',
 '16897802586': '15851984185',
 '17905765747': '15509453235',
 '15815448684': '13511782979',
 '18761125559': '29829200532',
 '23368682664': '10558188883',
 '20139307521': '10558877001',
 '15980707221': '9366106978',
 '18848038068': '9366106978',
 '33503207262': '9366106978',
 '28700427704': '29823042699',
 '9816946087': '12550186404',
 '9817287472': '12550186404',
 '9817320084': '12550186404',
 '15220484102': '9363260011',
 '32916862310': '9848087097',
 '9816996375': '25474295641',
 '18652842313': '25474295641',
 '12293065119': '10087115267',
 '12344587778': '13560692584',
 '13525574943': '9791127830',
 '12002788421': '10925369261',
 '16897801878': '10925369261',
 '23247426827': '10925369261',
 '32114225970': '10925369261',
 '16271223103': '10203327033',
 '22813841238': '10203327033',
 '28700923268': '10203327033',
 '18380960115': '29910128809',
 '18850648467': '29910128809',
 '18244772871': '9366186113',
 '13913192061': '9366106953',
 '9816991496': '25477992089',
 '9816991493': '9366095993',
 '9817306709': '9366095993',
 '9816981919': '9366140758',
 '29547220914': '9366140758',
 '10773449015': '9362275418',
 '13981816212': '9362275418',
 '14211779904': '9362275418',
 '16913143986': '9362275418',
 '19249538705': '9362275418',
 '32387026438': '9362275418',
 '32387026986': '9362275418',
 '32406302863': '9362275418',
 '9816996376': '9355661206',
 '9816996377': '9355661206',
 '30366315268': '12550301975',
 '9817339731': '16281658149',
 '18110061232': '29915136905',
 '13160765450': '17771169951',
 '12258530565': '14157684032',
 '18291571379': '12080565822',
 '9817320087': '29832756755',
 '20308836902': '29832756755',
 '22395214925': '29832756755',
 '11636340280': '10332795506',
 '9978555209': '9915968638',
 '12705156417': '9915968638',
 '9816940667': '9366069360',
 '9816958785': '9366069360',
 '9816958791': '9366069360',
 '9817297166': '9366069360',
 '9817306704': '9366069360',
 '12705678126': '9366069360',
 '13539369802': '9366069360',
 '15449480087': '9366069360',
 '16913001315': '9366069360',
 '21898600538': '9366069360',
 '31711896177': '9366069360',
 '9816953952': '9366155052',
 '9816981921': '9366155052',
 '9817292296': '9366155052',
 '9816981924': '9960233587',
 '9816996388': '9960233587',
 '12579262476': '9960233587',
 '12653014188': '9960233587',
 '16897800343': '9960233587',
 '31085879129': '26636807445',
 '28525080726': '25139082421',
 '22997393587': '21945567259',
 '17877535399': '19389427512',
 '15340342049': '17455265889',
 '33735737768': '16275369508',
 '33741931267': '16275369508',
 '33758455618': '16275369508',
 '11310773651': '10275149736',
 '14211778624': '9366155376',
 '9816981923': '29833227664',
 '9816996384': '9366119472',
 '12645534483': '9366124124',
 '9816981926': '9366069355',
 '9817334079': '9366095989',
 '9816972349': '9366059417',
 '9816986924': '9366059417',
 '9816986925': '9366059417',
 '9817306708': '9366059417',
 '9817320083': '9366059417',
 '15813731177': '9366059417',
 '16913141908': '9366059417',
 '9816986922': '9360510226',
 '9817329963': '9360510226',
 '18034263644': '9354729863',
 '18156129080': '21636407854',
 '18653885818': '21636407854',
 '31094685962': '21636407854',
 '12271860060': '14197527584',
 '9816996387': '9895825775',
 '9817334084': '12551118995',
 '12205858729': '12551118995',
 '9816991498': '9360534698',
 '9816996381': '9360534698',
 '9817297174': '9360534698',
 '21230109099': '10558176301',
 '11764516988': '10203312765',
 '30364426407': '25282174727',
 '13913191582': '29951656069',
 '17528464942': '9366173222',
 '9817297170': '9366106647',
 '9817329960': '9366106647',
 '9816968254': '29912622494',
 '9817292300': '29912622494',
 '9817320091': '29912622494',
 '12916835594': '29912622494',
 '12920180250': '29912622494',
 '33166281555': '28518382352',
 '18150751609': '19633787147',
 '14531674916': '16881549712',
 '18033986897': '16275393461',
 '13982095242': '15980488354',
 '13242199078': '15663659824',
 '12550652832': '13838898789',
 '16327776692': '25486704710',
 '18150342993': '12538423626',
 '29539000838': '10558856614',
 '13926987286': '10558861961',
 '18151202212': '10558078093',
 '16818375024': '10348289177',
 '17449503780': '9366155367',
 '21173004363': '10558020668',
 '13507359857': '15028171942',
 '14210952201': '15028171942',
 '14211779472': '15028171942',
 '28880509079': '25491277907',
 '29539001767': '25284499468',
 '16183052809': '18181299046',
 '14008449290': '25481208416',
 '14229843222': '25481208416',
 '19091989353': '15566796315',
 '16236300725': '9366129039',
 '23247275647': '9366087789',
 '23247429695': '9366087789',
 '29371084041': '25495937396',
 '30658873758': '9366087789',
 '9816968251': '9366136381',
 '9817329965': '9366099382',
 '9816940658': '9366069350',
 '9816972354': '9366069350',
 '12205687198': '9366069350',
 '13537607969': '9366069350',
 '16897886791': '9366069350',
 '9816953950': '9360792947',
 '9817324809': '9360792947',
 '9817324817': '9360792947',
 '9979409061': '9360792947',
 '15690903128': '9360792947',
 '16913144981': '9360792947',
 '30658872107': '9360792947',
 '30658872628': '9360792947',
 '30678155410': '9360792947',
 '10795413573': '9354077599',
 '12927835701': '9354077599',
 '16166893955': '25495937396',
 '18761359228': '25495937396',
 '12291872627': '13555176798',
 '15801579543': '17667781721',
 '9817311103': '9366091669',
 '31735800916': '17771239191',
 '19244602278': '12551531268',
 '18034258760': '19522936440',
 '29538999969': '25074205562',
 '13554628108': '15784196677',
 '19091568939': '15566796315',
 '19091753027': '15566796315',
 '19091753377': '15566796315',
 '19091753578': '15566796315',
 '19091774126': '15566796315',
 '19091775661': '15566796315',
 '19091987753': '15566796315',
 '19091988652': '15566796315',
 '19091989146': '15566796315',
 '19091996932': '15566796315',
 '19091997026': '15566796315',
 '19091997448': '15566796315',
 '21721674246': '15566796315',
 '21757317536': '15566796315',
 '21820261436': '15566796315',
 '21820305669': '15566796315',
 '29386126911': '15566796315',
 '29386765139': '15566796315',
 '29386765884': '15566796315',
 '29386766607': '15566796315',
 '29386780450': '15566796315',
 '29386780598': '15566796315',
 '29393304473': '15566796315',
 '10784175217': '9915992218',
 '18034261826': '9366131970',
 '18151205192': '21142568800',
 '9816946082': '9366168475',
 '9816958782': '9366168475',
 '9816991492': '9366168475',
 '9817315486': '9366168475',
 '15270815807': '9366168475',
 '15271115588': '9366168475',
 '18761410692': '23951465389',
 '9817334089': '9366128722',
 '14796277431': '9366168189',
 '30366312740': '9366168187',
 '9816996379': '29927797786',
 '9816977206': '9366115743',
 '29770676800': '25817374614',
 '30188807349': '25817374614',
 '13205430316': '10548447576',
 '9816996390': '9366155053',
 '16327804563': '9366155053',
 '9817287478': '9366155051',
 '9816986921': '9366136382',
 '9816977205': '9366087512',
 '9817329959': '29931840062',
 '18821499312': '17772140083',
 '18051284292': '17556648076',
 '14785508475': '15353794188',
 '15361319218': '15354435846',
 '22549228912': '25471507563',
 '32144763302': '18076792668',
 '18693596260': '9823974068',
 '9816972344': '9366140755',
 '9816940663': '9366069359',
 '9817311105': '29289850721',
 '13981724210': '29289850721',
 '17528652412': '18941327232',
 '17028928942': '18766274138',
 '19547859877': '17771177794',
 '29903516742': '17771177794',
 '29909536831': '17771177794',
 '29909537170': '17771177794',
 '33506737561': '10558884431',
 '33587003023': '10558168700',
 '22372859798': '21963980673',
 '15220482129': '12080219299',
 '16909950888': '10557621106',
 '30366314920': '10150061331',
 '9816940656': '9366106649',
 '20243210618': '21469030261',
 '18758014821': '20302482346',
 '16302163578': '17669207968',
 '15961145256': '25474139980',
 '15893733472': '17920342609',
 '15799352169': '17690646798',
 '16235870476': '17690646798',
 '21197775645': '15767544760',
 '18151280777': '15581733166',
 '18380519512': '9838063114',
 '15797615118': '29543474616',
 '16913145882': '29543474616',
 '21900634765': '29543474616'}

### Add a company ID column in the deals dataset for table merging

In [25]:
### record ID is the unique deal ID
### first convert it into string type to match the datatype in the dictionary
deals['Record ID'] = deals['Record ID'].astype(str)

#### create a company for company id based on the dictionary using mapping function

deals['Company ID'] = deals['Record ID'].map(deal_to_company)

### Merge the deals dataset and the companies dataset

commpany id from the deals table: 'Company ID'

company id from the company table: 'Record ID'

In [27]:
### convert the integer type to string type for Record ID
companies['Record ID'] = companies['Record ID'].astype(str)


deals_merged = pd.merge(left = deals, right = companies, left_on ='Company ID'  ,right_on ='Record ID' , how = 'left')

In [29]:
# deals_merged.columns

### The deals_merged dataset now contains both the deals inoformation and the company information. You can now go ahead with data preprocessing to handle all missing values, categorical data encoding, feature selection, feature scaling, and etc, and eventually build models to solve a specific problem.

In [29]:
#### only keep the data where is deal closed is true

df = deals_merged[deals_merged['Is Deal Closed?']==True]

In [41]:
df.columns

Index(['Weighted amount', 'Deal Description',
       'Cumulative time in "BANT Deal. Pain ID'ed (Sales Pipeline)" (HH:mm:ss)',
       'Cumulative time in "Opportunity (Sales Pipeline)" (HH:mm:ss)',
       'Days to close', 'Deal Score', 'Close Date_x',
       'Deal source attribution 2',
       'Cumulative time in "In Trial - Trial in Progress (Sales Pipeline)" (HH:mm:ss)',
       'Contract Start Date',
       'Cumulative time in "Partner Referrals  (Sales Pipeline)" (HH:mm:ss)',
       'Cumulative time in "Closed Lost (Sales Pipeline)" (HH:mm:ss)',
       'Cumulative time in "Deep Dive. PSP Drafted (Sales Pipeline)" (HH:mm:ss)',
       'Pipeline', 'Record ID_x', 'Forecast category',
       'Original Traffic Source', 'Associated Company_x', 'Deal owner',
       'Annual contract value', 'Is Closed (numeric)',
       'Amount in company currency', 'Annual recurring revenue',
       'Monthly recurring revenue', 'Deal probability',
       'Associated Company (Primary)', 'Is Closed Won', 'Forecast probability',
       'Contract End Date_x', 'Last Activity Date', 'Contract Term (Months)',
       'Trial Start date', 'Is closed lost',
       'Weighted amount in company currency', 'Is Deal Closed?',
       'Trial End Date', 'Deal Name', 'Amount',
       'Cumulative time in "Closed Trial (Sales Pipeline)" (HH:mm:ss)',
       'Forecast amount',
       'Cumulative time in "Negotiation (Sales Pipeline)" (HH:mm:ss)',
       'Is Open (numeric)',
       'Cumulative time in "Renewals  (Sales Pipeline)" (HH:mm:ss)',
       'Create Date_x',
       'Cumulative time in "Contract Sent (Sales Pipeline)" (HH:mm:ss)',
       'Total contract value', 'Last Modified Date_x',
       'Cumulative time in "Closed Won (Sales Pipeline)" (HH:mm:ss)',
       'Deal Stage', 'Deal Type', 'Company ID', 'Parent Company', 'CCaaS',
       'Annual Revenue', 'Target Account', 'Associated Contact',
       'Number of Form Submissions', 'Total Agents', 'Web Technologies',
       'Close Date_y', '# of Agents Total', 'Number of times contacted',
       'Contact with Primary Company', 'ICP Fit Level', 'Revenue range',
       '# of Agents Contracted', 'Record ID_y', 'Time Zone',
       'Primary Industry', 'Number of Pageviews', 'Primary Company',
       'Year Founded', 'ICP', 'Industry group', 'Segmentation', 'LMS System',
       'SymTrain Use Cases', 'Associated Company_y', 'BPO', 'SSO Application',
       'State/Region', 'SymTrain Product', 'Contract End Date_y',
       'SSO Implemented?', 'Consolidated Industry', 'Type',
       'Number of Employees', 'BPO Program', 'Primary Sub-Industry',
       'Number of Sessions', 'WFM', 'Country/Region', 'Industry',
       'Create Date_y', 'Company name', 'Last Modified Date_y',
       'BPO Program Tier'],
      dtype='object')

In [31]:
### Is Close Won is that we're trying to predict

### True: a successful deal
### false: deal lost
df['Is Closed Won'].value_counts()

Is Closed Won
False    266
True     158
Name: count, dtype: int64

In [33]:
### is closed won is the opposite of is closed lost, make sure you have dropped both columns in your X

np.mean(df['Is Closed Won'] != df['Is closed lost'])

1.0

In [35]:
### check the percentage of missing values, drop the columns if there are too many missing columns
dict(df.isna().mean())

{'Weighted amount': 0.04716981132075472,
 'Deal Description': 0.2028301886792453,
 'Cumulative time in "BANT Deal. Pain ID\'ed (Sales Pipeline)" (HH:mm:ss)': 0.5518867924528302,
 'Cumulative time in "Opportunity (Sales Pipeline)" (HH:mm:ss)': 0.9599056603773585,
 'Days to close': 0.0,
 'Deal Score': 1.0,
 'Close Date_x': 0.0,
 'Deal source attribution 2': 0.014150943396226415,
 'Cumulative time in "In Trial - Trial in Progress (Sales Pipeline)" (HH:mm:ss)': 0.8985849056603774,
 'Contract Start Date': 0.8372641509433962,
 'Cumulative time in "Partner Referrals  (Sales Pipeline)" (HH:mm:ss)': 0.9528301886792453,
 'Cumulative time in "Closed Lost (Sales Pipeline)" (HH:mm:ss)': 0.9952830188679245,
 'Cumulative time in "Deep Dive. PSP Drafted (Sales Pipeline)" (HH:mm:ss)': 0.9174528301886793,
 'Pipeline': 0.0,
 'Record ID_x': 0.0,
 'Forecast category': 0.0,
 'Original Traffic Source': 0.03537735849056604,
 'Associated Company_x': 0.049528301886792456,
 'Deal owner': 0.0047169811320754715,
 'Annual contract value': 1.0,
 'Is Closed (numeric)': 0.0,
 'Amount in company currency': 0.04716981132075472,
 'Annual recurring revenue': 1.0,
 'Monthly recurring revenue': 1.0,
 'Deal probability': 0.0,
 'Associated Company (Primary)': 0.049528301886792456,
 'Is Closed Won': 0.0,
 'Forecast probability': 1.0,
 'Contract End Date_x': 0.8372641509433962,
 'Last Activity Date': 0.4009433962264151,
 'Contract Term (Months)': 0.839622641509434,
 'Trial Start date': 0.9221698113207547,
 'Is closed lost': 0.0,
 'Weighted amount in company currency': 0.04716981132075472,
 'Is Deal Closed?': 0.0,
 'Trial End Date': 0.9174528301886793,
 'Deal Name': 0.0,
 'Amount': 0.04716981132075472,
 'Cumulative time in "Closed Trial (Sales Pipeline)" (HH:mm:ss)': 0.9669811320754716,
 'Forecast amount': 0.04716981132075472,
 'Cumulative time in "Negotiation (Sales Pipeline)" (HH:mm:ss)': 0.8042452830188679,
 'Is Open (numeric)': 0.0,
 'Cumulative time in "Renewals  (Sales Pipeline)" (HH:mm:ss)': 0.9127358490566038,
 'Create Date_x': 0.0,
 'Cumulative time in "Contract Sent (Sales Pipeline)" (HH:mm:ss)': 0.8301886792452831,
 'Total contract value': 1.0,
 'Last Modified Date_x': 0.0,
 'Cumulative time in "Closed Won (Sales Pipeline)" (HH:mm:ss)': 0.9716981132075472,
 'Deal Stage': 0.0,
 'Deal Type': 0.0,
 'Company ID': 0.049528301886792456,
 'Parent Company': 0.9716981132075472,
 'CCaaS': 0.8655660377358491,
 'Annual Revenue': 0.07547169811320754,
 'Target Account': 0.9150943396226415,
 'Associated Contact': 0.06132075471698113,
 'Number of Form Submissions': 0.06132075471698113,
 'Total Agents': 1.0,
 'Web Technologies': 0.06839622641509434,
 'Close Date_y': 0.5094339622641509,
 '# of Agents Total': 0.6886792452830188,
 'Number of times contacted': 0.06367924528301887,
 'Contact with Primary Company': 0.06132075471698113,
 'ICP Fit Level': 0.4386792452830189,
 'Revenue range': 1.0,
 '# of Agents Contracted': 0.7476415094339622,
 'Record ID_y': 0.049528301886792456,
 'Time Zone': 0.07547169811320754,
 'Primary Industry': 0.25235849056603776,
 'Number of Pageviews': 0.06132075471698113,
 'Primary Company': 1.0,
 'Year Founded': 0.10141509433962265,
 'ICP': 0.7688679245283019,
 'Industry group': 1.0,
 'Segmentation': 0.6297169811320755,
 'LMS System': 1.0,
 'SymTrain Use Cases': 0.9976415094339622,
 'Associated Company_y': 0.9599056603773585,
 'BPO': 0.8844339622641509,
 'SSO Application': 1.0,
 'State/Region': 0.07783018867924528,
 'SymTrain Product': 1.0,
 'Contract End Date_y': 0.7429245283018868,
 'SSO Implemented?': 0.9292452830188679,
 'Consolidated Industry': 0.049528301886792456,
 'Type': 0.2641509433962264,
 'Number of Employees': 0.07075471698113207,
 'BPO Program': 0.9174528301886793,
 'Primary Sub-Industry': 0.42924528301886794,
 'Number of Sessions': 0.06132075471698113,
 'WFM': 0.8207547169811321,
 'Country/Region': 0.07075471698113207,
 'Industry': 0.06839622641509434,
 'Create Date_y': 0.049528301886792456,
 'Company name': 0.049528301886792456,
 'Last Modified Date_y': 0.049528301886792456,
 'BPO Program Tier': 0.9834905660377359}

In [81]:
# df['Days to close']

In [ ]:
### categorical data encoding, I would sugget use label encoding even for the nominal data if it comes with too many categories

### Suggested columns to keep for input data X: 'Amount', 'Annual Revenue', 'Deal Type', 'Country/Region', 'Days to close', 'Primary Industry'....

In [ ]:
#### create X and y
y = df['Is Closed Won']
### X should not include any columns that are the same or the opposite of   the target columns

In [88]:
#### modeling